/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formlar;

import entity.db_kullanici;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import veritabani.DatabaseConnection;

/**
 *
 * @author s_a-i
 */
public class ana_sayfa extends javax.swing.JFrame {

    /**
     * Creates new form ana_sayfa
     */
    
    
    public ana_sayfa() {
        
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_musteri = new javax.swing.JButton();
        btn_arac = new javax.swing.JButton();
        btn_aracalis = new javax.swing.JButton();
        btn_aracsatis = new javax.swing.JButton();
        btn_marka = new javax.swing.JButton();
        btn_model = new javax.swing.JButton();
        btn_renk = new javax.swing.JButton();
        btn_kategori = new javax.swing.JButton();
        btn_adres = new javax.swing.JButton();
        btn_mustmodul = new javax.swing.JButton();
        btn_rapor = new javax.swing.JButton();
        lbl_sol = new javax.swing.JLabel();
        lbl_sag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        link_cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araç Satış Otomasyonu / Ana Sayfa");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        btn_musteri.setBackground(java.awt.SystemColor.textHighlight);
        btn_musteri.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_musteri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/cust.png"))); // NOI18N
        btn_musteri.setText("MÜŞTERİ TABLOSU");
        btn_musteri.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_musteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteriActionPerformed(evt);
            }
        });

        btn_arac.setBackground(java.awt.SystemColor.textHighlight);
        btn_arac.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_arac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/front.png"))); // NOI18N
        btn_arac.setText("ARAÇ TABLOSU");
        btn_arac.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_arac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aracActionPerformed(evt);
            }
        });

        btn_aracalis.setBackground(java.awt.SystemColor.textHighlight);
        btn_aracalis.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_aracalis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/le.png"))); // NOI18N
        btn_aracalis.setText("ARAÇ-ALIŞ");
        btn_aracalis.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_aracalis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aracalisActionPerformed(evt);
            }
        });

        btn_aracsatis.setBackground(java.awt.SystemColor.textHighlight);
        btn_aracsatis.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_aracsatis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/right.png"))); // NOI18N
        btn_aracsatis.setText("ARAÇ-SATIŞ");
        btn_aracsatis.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_aracsatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aracsatisActionPerformed(evt);
            }
        });

        btn_marka.setBackground(java.awt.SystemColor.textHighlight);
        btn_marka.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_marka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/marka.png"))); // NOI18N
        btn_marka.setText("MARKA TABLOSU");
        btn_marka.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_marka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_markaActionPerformed(evt);
            }
        });

        btn_model.setBackground(java.awt.SystemColor.textHighlight);
        btn_model.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_model.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/model.png"))); // NOI18N
        btn_model.setText("MODEL TABLOSU");
        btn_model.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modelActionPerformed(evt);
            }
        });

        btn_renk.setBackground(java.awt.SystemColor.textHighlight);
        btn_renk.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_renk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/color.png"))); // NOI18N
        btn_renk.setText("RENK TABLOSU");
        btn_renk.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_renk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_renkActionPerformed(evt);
            }
        });

        btn_kategori.setBackground(java.awt.SystemColor.textHighlight);
        btn_kategori.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/kat.png"))); // NOI18N
        btn_kategori.setText("KATEGORİ TABLOSU");
        btn_kategori.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kategoriActionPerformed(evt);
            }
        });

        btn_adres.setBackground(java.awt.SystemColor.textHighlight);
        btn_adres.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_adres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/adres.png"))); // NOI18N
        btn_adres.setText("ADRES TABLOSU");
        btn_adres.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adresActionPerformed(evt);
            }
        });

        btn_mustmodul.setBackground(java.awt.SystemColor.textHighlight);
        btn_mustmodul.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_mustmodul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/users.png"))); // NOI18N
        btn_mustmodul.setText("MÜŞTERİ MODÜLÜ");
        btn_mustmodul.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_mustmodul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mustmodulActionPerformed(evt);
            }
        });

        btn_rapor.setBackground(java.awt.SystemColor.textHighlight);
        btn_rapor.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_rapor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/rapor.png"))); // NOI18N
        btn_rapor.setText("RAPOR FORMU");
        btn_rapor.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_rapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raporActionPerformed(evt);
            }
        });

        lbl_sol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/car5.png"))); // NOI18N

        lbl_sag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/car6.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.textHighlight);
        jLabel1.setText("Nesneye Yönelik Yazılım Mühendisliği Dersi Projesi.");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setText("ARAÇ SATIŞ OTOMASYONU/2019.");

        txtarea.setEditable(false);
        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtarea.setForeground(java.awt.SystemColor.textHighlight);
        txtarea.setRows(5);
        txtarea.setText("1. Sağa Dönüşte Yayaya Yol Verin\n\n2. Yaya Geçitlerinde Yavaşlayın\n\n3. Başka Araçlarla Aranıza Mesafe Koyun\n\n4. Tek Yönlü Yollarda Tabelalara Bakarak İlerleyin\n\n5. Sadece Gerekli Durumlarda Korna Çalın\n\n6. Alkollü Halde Araç Kullanmayın\n\n7. Hız Kurallarına Dikkat Edin, Aşırı Hızdan Kaçının\n\n8. Kullandığınız Şeride Dikkat Edin\n\n9. Hatalı Sollamalardan Kaçının\n\n10.Emniyet kemerinizi takın");
        txtarea.setEnabled(false);
        jScrollPane1.setViewportView(txtarea);

        label.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        label.setForeground(java.awt.Color.gray);
        label.setText("TRAFİK KURALLARI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_adres, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(btn_mustmodul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_musteri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_rapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_kategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(258, 258, 258)
                                        .addComponent(label)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_model, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(btn_marka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_renk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_aracsatis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_aracalis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_arac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_sol)
                        .addGap(87, 87, 87)
                        .addComponent(lbl_sag)
                        .addGap(339, 339, 339))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sag, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_arac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_musteri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_mustmodul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_aracalis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_adres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_aracsatis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_renk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_rapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_marka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_model, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenu1.setText("Program");
        jMenu1.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Araç");
        jMenu2.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Müşteri");
        jMenu3.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tanımlamalar");
        jMenu4.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Hakkımızda");
        jMenu5.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Faydalı Linkler");
        jMenu6.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Çıkış");

        link_cikis.setText("Çıkış Yap");
        link_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_cikisActionPerformed(evt);
            }
        });
        jMenu7.add(link_cikis);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void link_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_cikisActionPerformed
        this.setVisible(false);
        giris_formu g = new giris_formu();
        g.setVisible(true);
        JOptionPane.showMessageDialog(this, "Başarıyla Çıkış Yaptınız!");
    }//GEN-LAST:event_link_cikisActionPerformed

    
    private void btn_raporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raporActionPerformed
        
    }//GEN-LAST:event_btn_raporActionPerformed

    private void btn_mustmodulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mustmodulActionPerformed
        this.setVisible(false);
        musteri_arac_formu maf = new musteri_arac_formu();
        maf.setVisible(true);

    }//GEN-LAST:event_btn_mustmodulActionPerformed

    private void btn_adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adresActionPerformed
        adres_formu af = new adres_formu();
        this.setVisible(false);
        af.setVisible(true);
    }//GEN-LAST:event_btn_adresActionPerformed

    private void btn_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kategoriActionPerformed
        this.setVisible(false);
        kategori_formu k = new kategori_formu();
        k.setVisible(true);
    }//GEN-LAST:event_btn_kategoriActionPerformed

    private void btn_renkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_renkActionPerformed
        this.setVisible(false);
        renk_formu r = new renk_formu();
        r.setVisible(true);
    }//GEN-LAST:event_btn_renkActionPerformed

    private void btn_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modelActionPerformed
        this.setVisible(false);
        model_formu m = new model_formu();
        m.setVisible(true);
    }//GEN-LAST:event_btn_modelActionPerformed

    private void btn_markaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_markaActionPerformed
        this.setVisible(false);
        marka_formu m = new marka_formu();
        m.setVisible(true);
    }//GEN-LAST:event_btn_markaActionPerformed

    private void btn_aracsatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aracsatisActionPerformed
        arac_satis as = new arac_satis();
        this.setVisible(false);
        as.setVisible(true);
    }//GEN-LAST:event_btn_aracsatisActionPerformed

    private void btn_aracalisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aracalisActionPerformed
        this.setVisible(false);
        arac_alis aa = new arac_alis();
        aa.setVisible(true);
    }//GEN-LAST:event_btn_aracalisActionPerformed

    private void btn_aracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aracActionPerformed
        this.setVisible(false);
        arac_formu a = new arac_formu();
        a.setVisible(true);
    }//GEN-LAST:event_btn_aracActionPerformed

    private void btn_musteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteriActionPerformed
        this.setVisible(false);
        musteri_formu mf = new musteri_formu();
        mf.setVisible(true);
    }//GEN-LAST:event_btn_musteriActionPerformed

    public void renk_Degis() {
        Random r = new Random();
        Color rc1 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_arac.setBackground(rc1);
        Color rc2 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_aracalis.setBackground(rc2);
        Color rc3 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_aracsatis.setBackground(rc3);
        Color rc4 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_kategori.setBackground(rc4);
        Color rc5 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_marka.setBackground(rc5);
        Color rc6 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_model.setBackground(rc6);
        Color rc7 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_musteri.setBackground(rc7);
        Color rc8 = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        btn_renk.setBackground(rc8);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ana_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ana_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ana_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ana_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ana_sayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adres;
    private javax.swing.JButton btn_arac;
    private javax.swing.JButton btn_aracalis;
    private javax.swing.JButton btn_aracsatis;
    private javax.swing.JButton btn_kategori;
    private javax.swing.JButton btn_marka;
    private javax.swing.JButton btn_model;
    private javax.swing.JButton btn_musteri;
    private javax.swing.JButton btn_mustmodul;
    private javax.swing.JButton btn_rapor;
    private javax.swing.JButton btn_renk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl_sag;
    private javax.swing.JLabel lbl_sol;
    private javax.swing.JMenuItem link_cikis;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
