/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formlar;

import crud.kullanici_crud;
import entity.db_kullanici;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author s_a-i
 */
public class giris_formu extends javax.swing.JFrame {

    /**
     * Creates new form giris_formu
     */
    int sayac = 3;
    static db_kullanici k = new db_kullanici();

    public giris_formu() {

        initComponents();
        formu_temizle();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     *
     * @return
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        txt_sifre = new javax.swing.JPasswordField();
        btn_girisyap = new javax.swing.JButton();
        chb_sifre = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_kullaniciadi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araç Satış Otomasyonu / Giriş");
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);

        btn_girisyap.setBackground(new java.awt.Color(255, 102, 0));
        btn_girisyap.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_girisyap.setText("Giriş Yap");
        btn_girisyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisyapActionPerformed(evt);
            }
        });

        chb_sifre.setBackground(java.awt.SystemColor.scrollbar);
        chb_sifre.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        chb_sifre.setForeground(new java.awt.Color(0, 204, 255));
        chb_sifre.setText("Şifreyi Göster");
        chb_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_sifreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Kullanıcı Giriş Formu");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Kullanıcı Adı:");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Şifre:");

        txt_kullaniciadi.setToolTipText("");
        txt_kullaniciadi.setName(""); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${name}"), txt_kullaniciadi, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/cst.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_kullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(chb_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_girisyap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)))
                        .addGap(102, 102, 102))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_kullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chb_sifre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btn_girisyap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisyapActionPerformed
        ImageIcon i = new ImageIcon("src/ikonlar/basari.png");
        kullanici_crud cr = new kullanici_crud();
//        String ad = txt_kullaniciadi.getText();
//        String sifre = txt_sifre.getText();

        k.setKullanici_adi(txt_kullaniciadi.getText());
        k.setKullanici_sifre(txt_sifre.getText());
        List<db_kullanici> kL = cr.getList();
        if (cr.dogrulama(k.getKullanici_adi(), k.getKullanici_sifre()) != false) {
            JOptionPane.showMessageDialog(this, "Giriş Başarılı !", "Bilgilendirme Mesajı", JOptionPane.INFORMATION_MESSAGE, i);
            this.setVisible(false);
            if (k.getKullanici_adi().equals("özge")) {
                patron_sayfa p = new patron_sayfa();
                p.setVisible(true);
            } else {
                ana_sayfa a = new ana_sayfa();
                a.setVisible(true);

            }

        } else if (k.getKullanici_adi().equals("")) {
            JOptionPane.showMessageDialog(this, "Lütfen Kullanıcı Adını Boş Bırakmayın !", "Uyarı Mesajı", JOptionPane.WARNING_MESSAGE);
        } else if (k.getKullanici_sifre().equals("")) {
            JOptionPane.showMessageDialog(this, "Lütfen Şifreyi Boş Bırakmayın !", "Uyarı Mesajı", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Hatalı Deneme.Kalan Hak:" + --sayac, "Hata Mesajı", JOptionPane.ERROR_MESSAGE);
        }
        formu_temizle();
        if (sayac == 0) {
            JOptionPane.showMessageDialog(this, "Deneme Şansınız Bitti !", "Hata Mesajı", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }


    }//GEN-LAST:event_btn_girisyapActionPerformed

    private void chb_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_sifreActionPerformed
        if (chb_sifre.isSelected()) {
            txt_sifre.setEchoChar((char) 0);
        } else {
            txt_sifre.setEchoChar('*');
        }
    }//GEN-LAST:event_chb_sifreActionPerformed

    public final void formu_temizle() {
        txt_kullaniciadi.setText(null);
        txt_sifre.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris_formu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_girisyap;
    private javax.swing.JCheckBox chb_sifre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kullaniciadi;
    private javax.swing.JPasswordField txt_sifre;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
