/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formlar;

import crud.musteri_crud;
import entity.db_musteri;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s_a-i
 */
public class musteri_formu extends javax.swing.JFrame {

    /**
     * Creates new form musteri_formu
     */
    db_musteri m = new db_musteri();
    ImageIcon i = new ImageIcon("src/ikonlar/polis2.png");

    public musteri_formu() {
        initComponents();
        musteri_goster();
        kontrol();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo_musteri = new javax.swing.JTable();
        btn_temizle = new javax.swing.JButton();
        txt_tc = new javax.swing.JTextField();
        txt_gsm = new javax.swing.JTextField();
        btn_geri = new javax.swing.JButton();
        txt_mail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kaydet_musteri = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        txt_ad = new javax.swing.JTextField();
        btn_silme = new javax.swing.JButton();
        txt_soyad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araç Satış Otomasyonu / Müşteri");
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);

        tablo_musteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad", "Soyad", "Kimlik No", "Cep Telefonu", "E-Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo_musteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo_musteriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo_musteri);
        if (tablo_musteri.getColumnModel().getColumnCount() > 0) {
            tablo_musteri.getColumnModel().getColumn(0).setResizable(false);
            tablo_musteri.getColumnModel().getColumn(0).setPreferredWidth(5);
            tablo_musteri.getColumnModel().getColumn(1).setResizable(false);
            tablo_musteri.getColumnModel().getColumn(2).setResizable(false);
            tablo_musteri.getColumnModel().getColumn(3).setResizable(false);
            tablo_musteri.getColumnModel().getColumn(4).setResizable(false);
            tablo_musteri.getColumnModel().getColumn(5).setResizable(false);
        }

        btn_temizle.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_temizle.setText("Temizle");
        btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temizleActionPerformed(evt);
            }
        });

        btn_geri.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_geri.setText("Geri Dön");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Ad:");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Soyad:");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("TC Kimlik No:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Cep Telefonu:");

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("E-Mail:");

        btn_kaydet_musteri.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_kaydet_musteri.setText("Kaydet");
        btn_kaydet_musteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydet_musteriActionPerformed(evt);
            }
        });

        btn_guncelle.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_guncelle.setText("Güncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_silme.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_silme.setText("Sil");
        btn_silme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silmeActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/cst.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(206, 206, 206)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_gsm, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_kaydet_musteri, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_silme, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_kaydet_musteri)
                            .addComponent(btn_guncelle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_silme)
                            .addComponent(btn_temizle))))
                .addGap(2, 2, 2)
                .addComponent(btn_geri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void kontrol() {

        btn_guncelle.setVisible(false);
        btn_temizle.setVisible(false);
        btn_silme.setVisible(false);
        btn_kaydet_musteri.setVisible(true);
    }

    public void formu_temizle() {
        txt_ad.setText(null);
        txt_soyad.setText(null);
        txt_gsm.setText(null);
        txt_tc.setText(null);
        txt_mail.setText(null);
    }

    public void musteri_goster() {
        musteri_crud cr = new musteri_crud();
        List<db_musteri> mL = cr.listele();
        DefaultTableModel model = (DefaultTableModel) tablo_musteri.getModel();
        tablo_musteri.setFillsViewportHeight(true);
        Object[] row = new Object[6];

        mL.stream().map((mL1) -> {
            row[0] = mL1.getMusteri_id();
            return mL1;
        }).map((mL1) -> {
            row[1] = mL1.getMusteri_ad();
            return mL1;
        }).map((mL1) -> {
            row[2] = mL1.getMusteri_soyad();
            return mL1;
        }).map((mL1) -> {
            row[3] = mL1.getMusteri_tc();
            return mL1;
        }).map((mL1) -> {
            row[4] = mL1.getMusteri_tel();
            return mL1;
        }).map((mL1) -> {
            row[5] = mL1.getMusteri_email();
            return mL1;
        }).forEach((_item) -> {
            model.addRow(row);
        });

    }

    public void tabloyu_temizle() {
        tablo_musteri.setModel(new DefaultTableModel(null, new String[]{"ID", "Ad", "Soyad", "Kimlik No", "Cep Telefonu", "E-Mail"}));

        tablo_musteri.getColumnModel().getColumn(0).setResizable(false);
        tablo_musteri.getColumnModel().getColumn(0).setPreferredWidth(5);
        tablo_musteri.getColumnModel().getColumn(1).setResizable(false);
        tablo_musteri.getColumnModel().getColumn(2).setResizable(false);
        tablo_musteri.getColumnModel().getColumn(3).setResizable(false);
        tablo_musteri.getColumnModel().getColumn(4).setResizable(false);
        tablo_musteri.getColumnModel().getColumn(5).setResizable(false);
    }

    private void btn_kaydet_musteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydet_musteriActionPerformed
        musteri_crud cr = new musteri_crud();
        try {

            m.setMusteri_ad(txt_ad.getText().trim());
            m.setMusteri_soyad(txt_soyad.getText().trim());
            m.setMusteri_email(txt_mail.getText().trim());
            m.setMusteri_tc(Integer.parseInt(txt_tc.getText().trim()));
            m.setMusteri_tel(Integer.parseInt(txt_gsm.getText().trim()));
            DefaultTableModel model = (DefaultTableModel) tablo_musteri.getModel();
            Object[] row = new Object[6];
            cr.ekle(m);
            row[1] = m.getMusteri_ad();
            row[2] = m.getMusteri_soyad();
            row[3] = m.getMusteri_tc();
            row[4] = m.getMusteri_tel();
            row[5] = m.getMusteri_email();
            model.addRow(row);
            tabloyu_temizle();
            musteri_goster();
            formu_temizle();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "1.Hiçbir Alanı Boş Bırakmadığınızdan Emin Olun!\n2.Sayısal Değer İsteyen Alanlara Hatalı Giriş Yapmayın!", "Uyarı Penceresi", JOptionPane.INFORMATION_MESSAGE, i);

        }
    }//GEN-LAST:event_btn_kaydet_musteriActionPerformed

    private void tablo_musteriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo_musteriMouseClicked
        DefaultTableModel model = (DefaultTableModel) tablo_musteri.getModel();
        try {

            txt_ad.setText(model.getValueAt(tablo_musteri.getSelectedRow(), 1).toString());
            txt_soyad.setText(model.getValueAt(tablo_musteri.getSelectedRow(), 2).toString());
            txt_mail.setText(model.getValueAt(tablo_musteri.getSelectedRow(), 5).toString());
            txt_gsm.setText(model.getValueAt(tablo_musteri.getSelectedRow(), 4).toString());
            txt_tc.setText(model.getValueAt(tablo_musteri.getSelectedRow(), 3).toString());
            btn_kaydet_musteri.setVisible(false);
            btn_guncelle.setVisible(true);
            btn_temizle.setVisible(true);
            btn_silme.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablo_musteriMouseClicked

    private void btn_silmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silmeActionPerformed
        musteri_crud cr = new musteri_crud();
        DefaultTableModel model = (DefaultTableModel) tablo_musteri.getModel();
        try {
            int a = JOptionPane.showConfirmDialog(this,
                    "Silmek İstediğine Emin misin?", "Doğrulama Penceresi",
                    JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, i);
            if (a == 0) {
                m.setMusteri_id((int) model.getValueAt(tablo_musteri.getSelectedRow(), 0));
                cr.sil(m);
                model.removeRow(tablo_musteri.getSelectedRow());
                model.fireTableDataChanged();
                formu_temizle();
                kontrol();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tablodan Silinecek Müşteriyi Seçtiğinizden Emin Olun!", "Uyarı Penceresi", JOptionPane.INFORMATION_MESSAGE, i);

        }
    }//GEN-LAST:event_btn_silmeActionPerformed

    private void btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temizleActionPerformed
        // TODO add your handling code here:
        formu_temizle();
        kontrol();

    }//GEN-LAST:event_btn_temizleActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablo_musteri.getModel();
        musteri_crud cr = new musteri_crud();
        try {

            m.setMusteri_id((int) model.getValueAt(tablo_musteri.getSelectedRow(), 0));
            m.setMusteri_ad(txt_ad.getText());
            m.setMusteri_soyad(txt_soyad.getText());
            m.setMusteri_tc(Integer.parseInt(txt_tc.getText()));
            m.setMusteri_tel(Integer.parseInt(txt_gsm.getText()));
            m.setMusteri_email(txt_mail.getText());
            cr.guncelle(m);
            model.setValueAt(txt_ad.getText(), tablo_musteri.getSelectedRow(), 1);
            model.setValueAt(txt_soyad.getText(), tablo_musteri.getSelectedRow(), 2);
            model.setValueAt(txt_tc.getText(), tablo_musteri.getSelectedRow(), 3);
            model.setValueAt(txt_gsm.getText(), tablo_musteri.getSelectedRow(), 4);
            model.setValueAt(txt_mail.getText(), tablo_musteri.getSelectedRow(), 5);
            formu_temizle();
            kontrol();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "1.Tablodan Güncellenecek Müşteriyi Seçtiğinizden Emin Olun!\n2.Sayısal Değer İsteyen Alanlara Hatalı Giriş Yapmayın!", "Uyarı Penceresi", JOptionPane.INFORMATION_MESSAGE, i);

        }

    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        if (giris_formu.k.getKullanici_adi().equals("özge")) {
                patron_sayfa p = new patron_sayfa();
                this.setVisible(false);
                p.setVisible(true);
            } else {
            this.setVisible(false);
                ana_sayfa a = new ana_sayfa();
                a.setVisible(true);

            }
    }//GEN-LAST:event_btn_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteri_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteri_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteri_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteri_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteri_formu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geri;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_kaydet_musteri;
    private javax.swing.JButton btn_silme;
    private javax.swing.JButton btn_temizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablo_musteri;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_gsm;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_soyad;
    private javax.swing.JTextField txt_tc;
    // End of variables declaration//GEN-END:variables
}
