/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formlar;

import crud.arac_crud;
import crud.marka_crud;
import crud.model_crud;
import crud.musteri_crud;
import entity.db_arac;
import entity.db_musteri;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s_a-i
 */
public class musteri_arac_formu extends javax.swing.JFrame {

    /**
     * Creates new form musteri_arac_formu
     */
    arac_crud ac = new arac_crud();
    model_crud moc = new model_crud();
    marka_crud mac = new marka_crud();
    ImageIcon i = new ImageIcon("src/ikonlar/polis2.png");

    public musteri_arac_formu() {
        initComponents();
        musteriGoster();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_arac = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_musteri = new javax.swing.JTable();
        btn_geri = new javax.swing.JButton();
        btn_goster = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araç Satış Otomasyonu / Müşteri Modülü");
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);

        table_arac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MARKA", "MODEL", "FİYAT [TL]"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_arac);
        if (table_arac.getColumnModel().getColumnCount() > 0) {
            table_arac.getColumnModel().getColumn(0).setResizable(false);
            table_arac.getColumnModel().getColumn(1).setResizable(false);
            table_arac.getColumnModel().getColumn(2).setResizable(false);
            table_arac.getColumnModel().getColumn(3).setResizable(false);
        }

        table_musteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "AD", "SOYAD", "KİMLİK NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_musteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_musteriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_musteri);
        if (table_musteri.getColumnModel().getColumnCount() > 0) {
            table_musteri.getColumnModel().getColumn(0).setResizable(false);
            table_musteri.getColumnModel().getColumn(1).setResizable(false);
            table_musteri.getColumnModel().getColumn(2).setResizable(false);
            table_musteri.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_geri.setText("Geri");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        btn_goster.setText("Göster");
        btn_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gosterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ARAÇ TABLOSU");

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MÜŞTERİ TABLOSU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_geri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_goster))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btn_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_geri)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_musteriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_musteriMouseClicked

    }//GEN-LAST:event_table_musteriMouseClicked

    private void btn_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gosterActionPerformed
        tabloyu_temizle();
        DefaultTableModel model = (DefaultTableModel) table_musteri.getModel();
        DefaultTableModel model1 = (DefaultTableModel) table_arac.getModel();
        db_musteri m = new db_musteri();
        try {
            m.setMusteri_id((int) model.getValueAt(table_musteri.getSelectedRow(), 0));
        } catch (ArrayIndexOutOfBoundsException e) {
        }

        if (m.getMusteri_id() > 0) {
            List<db_arac> aL = ac.hangiMusterinin(m.getMusteri_id());
            if (aL.isEmpty() == false) {

                Object[] row = new Object[4];
                for (int i = 0; i < aL.size(); i++) {
                    row[0] = aL.get(i).getArac_id();
                    row[1] = mac.marka_bul(aL.get(i).getArac_marka_id());
                    row[2] = moc.model_bul(aL.get(i).getArac_model_id());
                    row[3] = aL.get(i).getArac_fiyat();
                    model1.addRow(row);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Müşterinin hiç aracı yok!", "Uyarı Penceresi", JOptionPane.INFORMATION_MESSAGE, i);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Lütfen Müşteri Seçiniz!", "Uyarı Penceresi", JOptionPane.INFORMATION_MESSAGE, i);
        }
    }//GEN-LAST:event_btn_gosterActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        if (giris_formu.k.getKullanici_adi().equals("özge")) {
                patron_sayfa p = new patron_sayfa();
                this.setVisible(false);
                p.setVisible(true);
            } else {
            this.setVisible(false);
                ana_sayfa a = new ana_sayfa();
                a.setVisible(true);

            }
    }//GEN-LAST:event_btn_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public void tabloyu_temizle() {
        table_arac.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "MARKA", "MODEL", "FİYAT [TL]"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jScrollPane2.setViewportView(table_arac);

        if (table_arac.getColumnModel().getColumnCount() > 0) {
            table_arac.getColumnModel().getColumn(0).setResizable(false);
            table_arac.getColumnModel().getColumn(1).setResizable(false);
            table_arac.getColumnModel().getColumn(2).setResizable(false);
            table_arac.getColumnModel().getColumn(3).setResizable(false);
        }

    }

    public void musteriGoster() {
        musteri_crud cr = new musteri_crud();
        List<db_musteri> mL = cr.listele();
        DefaultTableModel model = (DefaultTableModel) table_musteri.getModel();
        table_musteri.setFillsViewportHeight(true);
        Object[] row = new Object[4];
        for (int i = 0; i < mL.size(); i++) {
            row[0] = mL.get(i).getMusteri_id();
            row[1] = mL.get(i).getMusteri_ad();
            row[2] = mL.get(i).getMusteri_soyad();
            row[3] = mL.get(i).getMusteri_tc();
            model.addRow(row);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteri_arac_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteri_arac_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteri_arac_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteri_arac_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteri_arac_formu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geri;
    private javax.swing.JButton btn_goster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_arac;
    private javax.swing.JTable table_musteri;
    // End of variables declaration//GEN-END:variables
}
