/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formlar;

import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author s_a-i
 */
public class patron_sayfa extends javax.swing.JFrame {

    /**
     * Creates new form ana_sayfa
     */
    ImageIcon i = new ImageIcon("src/ikonlar/patron.png");
    
    public patron_sayfa() {
        
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_musteri = new javax.swing.JButton();
        btn_arac = new javax.swing.JButton();
        btn_mustmodul = new javax.swing.JButton();
        btn_rapor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        link_cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araç Satış Otomasyonu / Ana Sayfa");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        btn_musteri.setBackground(java.awt.SystemColor.textHighlight);
        btn_musteri.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_musteri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/cust.png"))); // NOI18N
        btn_musteri.setText("MÜŞTERİ TABLOSU");
        btn_musteri.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_musteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteriActionPerformed(evt);
            }
        });

        btn_arac.setBackground(java.awt.SystemColor.textHighlight);
        btn_arac.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_arac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/front.png"))); // NOI18N
        btn_arac.setText("ARAÇ TABLOSU");
        btn_arac.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_arac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aracActionPerformed(evt);
            }
        });

        btn_mustmodul.setBackground(java.awt.SystemColor.textHighlight);
        btn_mustmodul.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_mustmodul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/users.png"))); // NOI18N
        btn_mustmodul.setText("MÜŞTERİ MODÜLÜ");
        btn_mustmodul.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_mustmodul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mustmodulActionPerformed(evt);
            }
        });

        btn_rapor.setBackground(java.awt.SystemColor.textHighlight);
        btn_rapor.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 12)); // NOI18N
        btn_rapor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/rapor.png"))); // NOI18N
        btn_rapor.setText("RAPOR FORMU");
        btn_rapor.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_rapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raporActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.textHighlight);
        jLabel1.setText("Nesneye Yönelik Yazılım Mühendisliği Dersi Projesi.");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setText("ARAÇ SATIŞ OTOMASYONU/2019.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/patron.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_musteri, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mustmodul, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_arac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_rapor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btn_musteri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btn_mustmodul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btn_rapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_arac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenu1.setText("Program");
        jMenu1.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Araç");
        jMenu2.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Müşteri");
        jMenu3.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tanımlamalar");
        jMenu4.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Hakkımızda");
        jMenu5.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Faydalı Linkler");
        jMenu6.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Çıkış");

        link_cikis.setText("Çıkış Yap");
        link_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_cikisActionPerformed(evt);
            }
        });
        jMenu7.add(link_cikis);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void link_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_cikisActionPerformed
        this.setVisible(false);
        giris_formu g = new giris_formu();
        g.setVisible(true);
        JOptionPane.showMessageDialog(this, "Başarıyla Çıkış Yaptınız!");
    }//GEN-LAST:event_link_cikisActionPerformed

    
    private void btn_raporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raporActionPerformed
        
    }//GEN-LAST:event_btn_raporActionPerformed

    private void btn_mustmodulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mustmodulActionPerformed
        this.setVisible(false);
        musteri_arac_formu maf = new musteri_arac_formu();
        maf.setVisible(true);

    }//GEN-LAST:event_btn_mustmodulActionPerformed

    private void btn_aracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aracActionPerformed
        this.setVisible(false);
        arac_formu a = new arac_formu();
        a.setVisible(true);
    }//GEN-LAST:event_btn_aracActionPerformed

    private void btn_musteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteriActionPerformed
        this.setVisible(false);
        musteri_formu mf = new musteri_formu();
        mf.setVisible(true);
    }//GEN-LAST:event_btn_musteriActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patron_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patron_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patron_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patron_sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patron_sayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arac;
    private javax.swing.JButton btn_musteri;
    private javax.swing.JButton btn_mustmodul;
    private javax.swing.JButton btn_rapor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem link_cikis;
    // End of variables declaration//GEN-END:variables
}
