/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formlar;

import crud.renk_crud;
import entity.db_arac_renk;
import java.awt.Color;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s_a-i
 */
public class renk_formu extends javax.swing.JFrame {

    /**
     * Creates new form renk_formu
     */
    db_arac_renk r = new db_arac_renk();
    renk_crud rc = new renk_crud();
    ImageIcon i = new ImageIcon("src/ikonlar/polis2.png");

    public renk_formu() {
        initComponents();
        renk_goster();
        kontrol();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_renkid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_renkadi = new javax.swing.JTextField();
        btn_kaydet = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_temizle = new javax.swing.JButton();
        btn_geri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo_renk = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araç Satış Otomasyonu / Renk");
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Renk ID:");

        txt_renkid.setEditable(false);
        txt_renkid.setText("Read Only");
        txt_renkid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_renkidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Renk Adı:");

        btn_kaydet.setText("Kaydet");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        btn_guncelle.setText("Güncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_sil.setText("Sil");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_temizle.setText("Temizle");
        btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temizleActionPerformed(evt);
            }
        });

        btn_geri.setText("Geri Dön");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        tablo_renk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Renk ID", "Renk Adı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo_renk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo_renkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo_renk);
        if (tablo_renk.getColumnModel().getColumnCount() > 0) {
            tablo_renk.getColumnModel().getColumn(0).setResizable(false);
            tablo_renk.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonlar/renk_big.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(150, 150, 150))
                                    .addComponent(txt_renkadi)
                                    .addComponent(txt_renkid, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(btn_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 35, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_guncelle)
                                    .addComponent(btn_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(453, 453, 453)
                                .addComponent(btn_geri))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addComponent(btn_geri))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_renkid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kaydet)
                            .addComponent(btn_guncelle))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_renkadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sil)
                            .addComponent(btn_temizle))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        this.setVisible(false);
        ana_sayfa a = new ana_sayfa();
        a.setVisible(true);
    }//GEN-LAST:event_btn_geriActionPerformed

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed

        r.setRenk_adi(txt_renkadi.getText().trim());
        if (!txt_renkadi.getText().equals("")) {
            rc.renk_kaydet(r);
            DefaultTableModel model = (DefaultTableModel) tablo_renk.getModel();
            Object[] row = new Object[2];
            row[1] = r.getRenk_adi();
            model.addRow(row);
            tabloyu_temizle();
            renk_goster();
            formu_temizle();
        } else {
            JOptionPane.showMessageDialog(this, "Renk Adı Alanını Boş Bırakmayın!", "Uyarı Penceresi", JOptionPane.INFORMATION_MESSAGE, i);
        }

    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temizleActionPerformed
        formu_temizle();
        kontrol();
    }//GEN-LAST:event_btn_temizleActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablo_renk.getModel();
        try {

            r.setRenk_id((int) (model.getValueAt(tablo_renk.getSelectedRow(), 0)));
            r.setRenk_adi(txt_renkadi.getText());
            rc.renk_guncelle(r);
            model.setValueAt(txt_renkadi.getText().trim(), tablo_renk.getSelectedRow(), 1);
            formu_temizle();
            kontrol();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tablodan Güncellenecek Rengi Seçtiğinizden Emin Olun!", "Uyarı Penceresi", JOptionPane.INFORMATION_MESSAGE, i);

        }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void tablo_renkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo_renkMouseClicked
        DefaultTableModel model = (DefaultTableModel) tablo_renk.getModel();
        try {

            txt_renkid.setText(model.getValueAt(tablo_renk.getSelectedRow(), 0).toString());
            txt_renkadi.setText(model.getValueAt(tablo_renk.getSelectedRow(), 1).toString());
            btn_guncelle.setVisible(true);
            btn_temizle.setVisible(true);
            btn_sil.setVisible(true);
            btn_kaydet.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablo_renkMouseClicked

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablo_renk.getModel();
        r.setRenk_id(Integer.parseInt(model.getValueAt(tablo_renk.getSelectedRow(), 0).toString()));
        rc.renk_sil(r);
        model.removeRow(tablo_renk.getSelectedRow());
        model.fireTableDataChanged();
        formu_temizle();
        kontrol();
    }//GEN-LAST:event_btn_silActionPerformed

    private void txt_renkidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_renkidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_renkidActionPerformed

    public void renk_goster() {
        List<db_arac_renk> rL = rc.getList();
        DefaultTableModel model = (DefaultTableModel) tablo_renk.getModel();
        tablo_renk.setFillsViewportHeight(true);
        Object[] row = new Object[2];
        for (int i = 0; i < rL.size(); i++) {
            row[0] = rL.get(i).getRenk_id();
            row[1] = rL.get(i).getRenk_adi();
            model.addRow(row);
        }

    }

    public void tabloyu_temizle() {
        tablo_renk.setModel(new DefaultTableModel(null, new String[]{"ID", "Renk Adı"}));
        tablo_renk.getColumnModel().getColumn(0).setResizable(false);
        tablo_renk.getColumnModel().getColumn(1).setResizable(false);

    }

    public void kontrol() {

        btn_guncelle.setVisible(false);
        btn_temizle.setVisible(false);
        btn_sil.setVisible(false);
        btn_kaydet.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public void formu_temizle() {

        txt_renkid.setText("Read Only");
        txt_renkadi.setText(null);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(renk_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(renk_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(renk_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(renk_formu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new renk_formu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geri;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_temizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablo_renk;
    private javax.swing.JTextField txt_renkadi;
    private javax.swing.JTextField txt_renkid;
    // End of variables declaration//GEN-END:variables
}
